# Multi-Agent System Configuration

llm:
  base_model: "microsoft/DialoGPT-medium"
  max_length: 512
  temperature: 0.7
  use_lora: false
  lora_adapters_path: "./models/adapters"

agents:
  memory_enabled: true
  rag_enabled: true
  default_timeout: 300
  
  dev_agent:
    temperature: 0.3
    max_length: 1024
    
  research_agent:
    temperature: 0.5
    max_length: 2048
    
  data_agent:
    temperature: 0.4
    max_length: 1024

vector_db:
  chroma:
    path: "./data/chroma"
    collection_rag: "rag_documents"
    collection_memory: "agent_memory"
    
multimodal:
  blip2_model: "Salesforce/blip2-opt-2.7b"
  whisper_model: "openai/whisper-base"
  
mlops:
  mlflow_tracking_uri: "mlruns"
  experiment_name: "multi-agent-system"
  log_metrics: true
  
api:
  host: "0.0.0.0"
  port: 8000
  cors_origins: ["*"]
  
safety:
  enabled: true
  filter_responses: true
  log_violations: true